language: node_js
node_js:
  - "0.11"
  - "0.10"

env:
  global:
    secure: "Puz/FowvKkvm1erFWtEdqNUwLoqVhyloElcXAWQYxKLXCf6JXpqEIqMANDcXvlzKB9cIw1Y/tTMeEaOlKYD2XxLdWCwTNrbug6Cd+8EfUC1LM8Or29SrfssKNg4ipvCak1wm52DiD2Bx1PsrjJkEsQn9ak1dudPj1xLPRKXQVzg="
    secure: "DCI5AwJqQxa+GqZaSGublRBYoX9Uz22KH19sDQeM5szOby8/NLV/ZjMHBGbM0lFvnf8WtsCok5gYPHqnBlgesvFaB3fkmeHG1Hw9ZGVuIpF3gSfMa5LYJBTJTPOw46FXCuqFI8H34dvbe8mZ8fTG0J7ZL4OitsEq0DxL8YUAn1M="

addons:
  sauce_connect: true

before_script:
  - ./go dev
  - mv example/config-travis.js example/config.js
  - mv test/config-travis.js test/config.js
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - curl "https://selenium.googlecode.com/files/selenium-server-standalone-2.38.0.jar" > /tmp/selenium.jar
  - java -jar /tmp/selenium.jar -host 127.0.0.1 &> /tmp/selenium.log &
  - sleep 20

script:
  - npm run test-examples
  - npm test
  - npm run test-integration
  - npm run test-security

after_failure:
  - cat /tmp/selenium.log
